# Generated by Django 5.1.3 on 2024-11-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('quantiy', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
